### ISSUE TITLE
Building the application with electron-builder, it doesn't work.

### ISSUE THREAD

**Issue by steinjonathan** [frankhale/electron-with-express#17]
Building the application with electron-builder, it doesn't work.
After installing, when run the app it don't get done the load, and the api are not work on browser in localhost:3000.

1. Install electron-builder
2. Install de dist .exe
3. run;

**Comment by frankhale** [comment]
This one is free for the taking to anyone that is interested in fixing this. If somebody does fix it please send a pull request with instructions and/or code changes. Thanks!

**Comment by frankhale** [comment]
This should not be much more difficult to get running than it was for using Electron Packager. That process was documented here: https://github.com/frankhale/electron-with-express#package-with-electron-packager

If you manage to run into issues and manage to resolve them please submit a pull request so that that information/code changes can be incorporated into master.
