### ISSUE TITLE
Not working after packaging with electron-packager

### ISSUE THREAD

**Issue by coderkidz** [frankhale/electron-with-express#4]
Hi, 
Thanks for such a great library. 
The app stopped working after packaging t with electron-packager. 
Not sure if I need to take any special step or not.

**Comment by frankhale** [comment]
Thanks for reporting this. I've never used Electron Packager so I think I'll probably take some time in the near future to see what's going on and how to best resolve it.

**Comment by VzqzAc** [comment]
Wouldn't that be for the extra node instance you need to run it? I mean, that electron-packager can't "package" it together for that, but I haven't used it before so I'm not really sure just guessing

**Comment by frankhale** [comment]
Yeah I'm thinking that is exactly what is happening. I'm going to play around with Electron packager tomorrow and see how to best resolve this.

**Comment by frankhale** [comment]
Just got it working with electron-packager. The only issue was the path to spawn node (which starts express).

In the code in index.html we need to add the following and then change the spawn path.

```javascript
app = require('electron').remote.app

...

node = spawn(".\\node.exe", ["./express-app/bin/www"], { cwd: app.getAppPath() })
```

I'll make a note of this in the README since it's desirable to continue to support `npm start` as well as make sure people are aware of how to run it using electron-packager if they so desire.

**Comment by frankhale** [comment]
It should be noted that Windows is assumed as the platform. Additional changes / info would need to be made in order to support other platforms.

51903e087166b7183dbee6847df59e472d90c1bd

**Comment by kgrosvenor** [comment]
Does the user need to have node js installed for this to work? .exe file isn't going to work on linux either, can this be extended?

**Comment by frankhale** [comment]
The user does not need to have Node installed for this to work. The README details that we ship our own Node executables along with the app so that we don't have to depend on if the user has it or not and so that we can start up a regular Node process outside of Electron in order to do work (eg. run the Express server). 

Have a look at the following section in the README: https://github.com/frankhale/electron-with-express#running-on-linux

**Comment by chetan-northout** [comment]
can you share Additional changes / info in order to support other platforms (linux and mac OS).

**Comment by frankhale** [comment]
I don't have a Mac but the info in the Linux section should work on Mac OS X. Just need to download the relevant Node package form nodejs.org.

https://github.com/frankhale/electron-with-express#running-on-linux
