### ISSUE TITLE
how would you make this work on linux?

### ISSUE THREAD

**Issue by mateo-io** [frankhale/electron-with-express#8]
Hello this is exactly what I want but I want to run it on linux and I'm kind of an electron noob. 

Has anyone already done that or know what changes I need to do in order to get it working.

Thanks

**Comment by frankhale** [comment]
Nothing in the example should be OS specific, it should just work on Linux. What issues are you experiencing?

**Comment by frankhale** [comment]
At any rate I will test today on Linux to see if there are any issues

**Comment by frankhale** [comment]
Just upgraded all dependencies and ran on Windows, everything is fine. Will test Linux when I get back home this afternoon.

![express-with-electron-screenshot](https://cloud.githubusercontent.com/assets/190154/26033693/668ad15c-387e-11e7-86ca-91fc5e303913.PNG)

**Comment by frankhale** [comment]
Need to make sure you download the node executable and it's shared library for Linux and put them in the root of the cloned repository like the screenshot above. It uses it's own Node to spawn the Express app. Of course you can change this if you want it to use the system installed Node but the general idea is that it'd be nice to bring our own Node in case the machine doesn't already have it.

**Comment by frankhale** [comment]
Okay currently testing in Linux and yes I can see how my instructions will need to be modified for running in Linux. I'm hoping to have this updated today.

**Comment by frankhale** [comment]
Okay it's working with just a very minimal change which I'll document shortly

![express-with-electron-linux-screenshot](https://cloud.githubusercontent.com/assets/190154/26037425/52cb1478-38c0-11e7-9905-709e3f1b0309.PNG)

**Comment by frankhale** [comment]
Just to clarify there is really no need to download a stand alone copy of Node unless you really want to. You can just use a regular install of node to spawn Express. Line 65 in index.html would need to be changed slightly to: 

```js
node = spawn("node", ["./express-app/bin/www"], { cwd: process.cwd() })
```

Otherwise if you prefer to do it like I do continue reading...

Downloading a standalone Linux build is slightly more annoying than the nicely statically linked Windows executables but just as easy to deal with.

So basically download Node (whatever build you want, I always use latest):

https://nodejs.org/dist/latest-v7.x/node-v7.10.0-linux-x64.tar.gz

Unpack it into the root of the cloned repository. Then create a symbolic link called 'node' at the same location.

```bash
ln -sf node-v7.10.0-linux-x64/bin/node node
```

Change line 65 in index.html to the following:

```javascript
node = spawn("./node", ["./express-app/bin/www"], { cwd: process.cwd() })
```

Here is a screenshot of what it should look like:

![express-with-electron-linux-folder-structure-screenshot](https://cloud.githubusercontent.com/assets/190154/26037547/13c20de2-38c3-11e7-9b89-8de2335bd3d4.png)

Then you can run it:

```bash
./node start-electron.js &
```

**Comment by frankhale** [comment]
README has been updated to reflect what was done here to run on Linux. 

Thank you for asking this!

Closing via 87c5e7aa945ef1cd9d1c3eed1f1bd43dc11d5149

**Comment by frankhale** [comment]
@mateo-io you good with these instructions?
